name: Update

on:
  schedule:
    - cron: '35 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: native
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
      - name: Set up nix
        run: |
          mkdir -p $HOME/.config/nix
          cat <<CONFIG > $HOME/.config/nix/nix.conf
          access-tokens = github.com=${{ secrets.ACCESS_TOKEN_GITHUB }}
          cores = 2
          max-jobs = 2
          CONFIG
      - name: Set up attic
        run: attic login --set-default chvp https://attic.chvp.be "${{ secrets.ATTIC_AUTH_TOKEN }}"
      - run: nix flake update
      - run: nix build -L --no-link .#packages.x86_64-linux.default
      - run: nix build -L --no-link .#devShells.x86_64-linux.default
      - run: nix eval --json ".#packages.x86_64-linux.default.outPath" | sed 's/"\(.*\)"/\1/' | attic push chvp --stdin
      - run: nix eval --json ".#devShells.x86_64-linux.default.outPath" | sed 's/"\(.*\)"/\1/' | attic push chvp --stdin
      - name: Commit and push
        if: ${{ success() }}
        run: |
          if [ "$(git status --porcelain=v1 | wc -l)" != "0" ]
          then
            git status --porcelain=v1
            git add .
            git -c "user.name=CharBOTte" -c "user.email=commit-bot@chvp.be" commit -m "Update dependencies"
            git push origin
          else
            echo "Nothing to commit"
          fi
